'use client'
import localFont from "next/font/local";
import { createContext, useState } from "react";
import Navbar from "./components/Navbar/Navbar";

export const searchContext=createContext();

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [search,setSearch]=useState("");
  const data = [
    {
      shopName: "Magma Repair Shop",
      city: "Lahore",
      image: "https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=600",
      desc: "Get your phone fixed by certified technicians. Convenient, reliable, and fast.",
      email: "magma@gmail.com",
      phone: "03034242421",
      address: "Muslim Town Street No 6, Lahore",
      android: true,
      apple: false,
      status: "verified",
      facebook: "www.magma.com",
      instagram: "magma222",
      tiktok: false
    },
    {
      shopName: "Quick Fix Electronics",
      city: "Karachi",
      image: "https://images.pexels.com/photos/1092645/pexels-photo-1092645.jpeg?auto=compress&cs=tinysrgb&w=600",
      desc: "Fast and affordable mobile repairs, with quality guaranteed.",
      email: "quickfix@electro.com",
      phone: "03055543321",
      address: "Karachi Tech Park, Karachi",
      android: true,
      apple: true,
      status: "unverified",
      facebook: "www.quickfix.com",
      instagram: "quickfix_electro",
      tiktok: true
    },
    {
      shopName: "Techies Hub",
      city: "Islamabad",
      image: "https://images.pexels.com/photos/1092648/pexels-photo-1092648.jpeg?auto=compress&cs=tinysrgb&w=600",
      desc: "Expert repairs for all your tech needs, with quick turnaround.",
      email: "techieshub@support.com",
      phone: "03012234456",
      address: "Tech Lane, Islamabad",
      android: true,
      apple: true,
      status: "verified",
      facebook: "www.techieshub.com",
      instagram: "techieshub_repair",
      tiktok: true
    },
    {
      shopName: "FastTech Mobile Repair",
      city: "Rawalpindi",
      image: "https://images.pexels.com/photos/1092653/pexels-photo-1092653.jpeg?auto=compress&cs=tinysrgb&w=600",
      desc: "Fast and reliable mobile phone repairs with great customer service.",
      email: "fasttech@repair.com",
      phone: "03087654321",
      address: "Rawalpindi Market, Rawalpindi",
      android: true,
      apple: false,
      status: "verified",
      facebook: "www.fasttechrepair.com",
      instagram: "fasttech_mobile",
      tiktok: false
    },
    {
      shopName: "Mobile Fixers",
      city: "Lahore",
      image: "https://images.pexels.com/photos/1092648/pexels-photo-1092648.jpeg?auto=compress&cs=tinysrgb&w=600",
      desc: "Professional phone repair services for all models and brands.",
      email: "mobilefixers@service.com",
      phone: "03099887766",
      address: "Township Road, Lahore",
      android: true,
      apple: true,
      status: "unverified",
      facebook: "www.mobilefixers.com",
      instagram: "mobilefixers_official",
      tiktok: true
    },
    {
      shopName: "Repair Nation",
      city: "Multan",
      image: "https://images.pexels.com/photos/1092645/pexels-photo-1092645.jpeg?auto=compress&cs=tinysrgb&w=600",
      desc: "Your one-stop solution for repairing all mobile devices.",
      email: "repairnation@help.com",
      phone: "03011223344",
      address: "Multan City Center, Multan",
      android: true,
      apple: true,
      status: "verified",
      facebook: "www.repairnation.com",
      instagram: "repairnation_mobile",
      tiktok: true
    },
    {
      shopName: "Magma Repair Shop",
      city: "Lahore",
      image: "https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=600",
      desc: "Get your phone fixed by certified technicians. Convenient, reliable, and fast.",
      email: "magma@gmail.com",
      phone: "03034242421",
      address: "Muslim Town Street No 6, Lahore",
      android: true,
      apple: false,
      status: "verified",
      facebook: "www.magma.com",
      instagram: "magma222",
      tiktok: false
    },
    {
      shopName: "Quick Fix Electronics",
      city: "Karachi",
      image: "https://images.pexels.com/photos/1092645/pexels-photo-1092645.jpeg?auto=compress&cs=tinysrgb&w=600",
      desc: "Fast and affordable mobile repairs, with quality guaranteed.",
      email: "quickfix@electro.com",
      phone: "03055543321",
      address: "Karachi Tech Park, Karachi",
      android: true,
      apple: true,
      status: "unverified",
      facebook: "www.quickfix.com",
      instagram: "quickfix_electro",
      tiktok: true
    },
    {
      shopName: "Techies Hub",
      city: "Islamabad",
      image: "https://images.pexels.com/photos/1092648/pexels-photo-1092648.jpeg?auto=compress&cs=tinysrgb&w=600",
      desc: "Expert repairs for all your tech needs, with quick turnaround.",
      email: "techieshub@support.com",
      phone: "03012234456",
      address: "Tech Lane, Islamabad",
      android: true,
      apple: true,
      status: "verified",
      facebook: "www.techieshub.com",
      instagram: "techieshub_repair",
      tiktok: true
    },
    {
      shopName: "Phone Surgeons",
      city: "Faisalabad",
      image: "https://images.pexels.com/photos/1092652/pexels-photo-1092652.jpeg?auto=compress&cs=tinysrgb&w=600",
      desc: "Fixing phones with precision and care, at affordable prices.",
      email: "phonesurgeons@repair.com",
      phone: "03066554433",
      address: "Faisalabad Tech Street, Faisalabad",
      android: true,
      apple: false,
      status: "unverified",
      facebook: "www.phonesurgeons.com",
      instagram: "phonesurgeons_official",
      tiktok: false
    },
    {
      shopName: "Techy Repairs",
      city: "Karachi",
      image: "https://images.pexels.com/photos/1092645/pexels-photo-1092645.jpeg?auto=compress&cs=tinysrgb&w=600",
      desc: "We fix your gadgets quickly and efficiently.",
      email: "techy@repairs.com",
      phone: "03055443322",
      address: "Karachi Tech Hub, Karachi",
      android: true,
      apple: true,
      status: "verified",
      facebook: "www.techyrepairs.com",
      instagram: "techy_repair",
      tiktok: true
    },
    {
      shopName: "RepairX",
      city: "Quetta",
      image: "https://images.pexels.com/photos/1092648/pexels-photo-1092648.jpeg?auto=compress&cs=tinysrgb&w=600",
      desc: "Professional repairs with guaranteed quality and speed.",
      email: "repairx@service.com",
      phone: "03011223344",
      address: "Quetta City Center, Quetta",
      android: true,
      apple: true,
      status: "verified",
      facebook: "www.repairx.com",
      instagram: "repairx_tech",
      tiktok: false
    }
  ]
  const filterdData=data.filter((shop)=> shop.city.toLowerCase().includes(search.toLowerCase()) )

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <searchContext.Provider value={{search,setSearch,filterdData}}>
          <Navbar/>
        {children}
         </searchContext.Provider>
      </body>
    </html>
  );
}
